//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.PeopleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/SimpleWcf")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string familyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string givenNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.familyNameField, value) != true)) {
                    this.familyNameField = value;
                    this.RaisePropertyChanged("familyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.givenNameField, value) != true)) {
                    this.givenNameField = value;
                    this.RaisePropertyChanged("givenName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeopleService.IPeople")]
    public interface IPeople {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeople/GetData", ReplyAction="http://tempuri.org/IPeople/GetDataResponse")]
        ConsoleApplication1.PeopleService.Person GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeople/GetData", ReplyAction="http://tempuri.org/IPeople/GetDataResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.PeopleService.Person> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeopleChannel : ConsoleApplication1.PeopleService.IPeople, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleClient : System.ServiceModel.ClientBase<ConsoleApplication1.PeopleService.IPeople>, ConsoleApplication1.PeopleService.IPeople {
        
        public PeopleClient() {
        }
        
        public PeopleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.PeopleService.Person GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.PeopleService.Person> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
